ukf_slam:
  ros__parameters:
    scan_topic: /robot1/scan
    odom_topic: /odometry/data

    sigmapoint:
      alpha: 0.015
      beta: 2.0
      kappa: 0.0

    P_base: [0.0000001, 0.000, 0.000,
             0.000, 0.0000001, 0.000,
             0.000, 0.000, 0.0000001]

    Q_scale:
      a: 0.01
      b: 0.01

    R: [0.0025, 0.0025]

    max_landmark: 150
    time_syns_period: 0.018
    new_landmark_corv_base: 0.0016

    segment_scan:
      range_thres: 0.2
      min_point: 9

    extract_curvature_points:
      neib_number: 5
      curvature_threshold: 0.185
      range_min: 0.5
      range_max: 10.0
    
    cluster_future:
     angle_threshold: 0.02

    association:
      chi2_threshold: 5.99
      range_raw_thes: 2.0
      angle_raw_thes: 0.5






